# Generated by Django 5.2.7 on 2025-10-31 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_artists', models.TextField(blank=True, help_text='Comma-seperated list of favorite artists')),
                ('favorite_genres', models.TextField(blank=True, help_text='Comma-seperated list of favorite music genres')),
                ('favorite_tracks', models.TextField(blank=True, help_text='Comma-seperated list of favorite tracks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Music Preferences',
            },
        ),
    ]
