# Generated by Django 5.2.7 on 2025-11-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicpreferences',
            name='favorite_artists',
            field=models.TextField(blank=True, help_text='Comma-separated list of favorite artists'),
        ),
        migrations.AlterField(
            model_name='musicpreferences',
            name='favorite_genres',
            field=models.TextField(blank=True, help_text='Comma-separated list of favorite music genres'),
        ),
        migrations.AlterField(
            model_name='musicpreferences',
            name='favorite_tracks',
            field=models.TextField(blank=True, help_text='Comma-separated list of favorite tracks'),
        ),
        migrations.CreateModel(
            name='SoundCloudArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundcloud_artists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
