# Generated by Django 5.2.8 on 2025-12-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='average_time_listened',
            field=models.IntegerField(blank=True, help_text='Average minutes listened per week', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='disambiguation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate this artist from 1 to 5 stars', null=True),
        ),
    ]
