"""
Django settings for Harmonet project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#z%-s1%bi6fkcnbl1x4r-0jsenlqt-4x$jyrp^4x_%2-!8hjxu'
database_url = os.environ.get('DATABASE_URL')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Spotify variables and client ID
SPOTIPY_CLIENT_ID = config('SPOTIPY_CLIENT_ID', default='')
SPOTIPY_CLIENT_SECRET = config('SPOTIPY_CLIENT_SECRET', default='')
#for testing use: https://cs4300-harmonet-accj.onrender.com  
#|| https://cs4300-harmonet-accj.onrender.com/user/spotify/callback/ 
#|| https://harmonets.org/user/spotify/callback/ 
#|| https://cs4300-harmonet-accj.onrender.com
SPOTIPY_REDIRECT_URI = "https://cs4300-harmonet-accj.onrender.com/user/spotify/callback/ "

ALLOWED_HOSTS = [
    'app-cs4300sanchez-19.devedu.io',
    'localhost',
    'editor-cs4300sanchez-19.devedu.io',
    'cs4300-harmonet-accj.onrender.com',
    '*', 
]
# '*' is a catch all for hosts, good to remove when done testing.

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Harmonet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Harmonet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#Testdatabase: postgresql://testdatabase_hhx7_user:9aWdqjNOLHfxUI1P1XETkbuvD9kGWoNe@dpg-d4aitdeuk2gs739g4ekg-a.oregon-postgres.render.com/testdatabase_hhx7
#realDatabase: postgresql://harmonet_database_user:qel7JegasDb20m2GztJp09ySNVIDmkEz@dpg-d4aigq1e2q1c73b0l70g-a.oregon-postgres.render.com/harmonet_database
DATABASES = {'default': dj_database_url.parse('postgresql://testdatabase_hhx7_user:9aWdqjNOLHfxUI1P1XETkbuvD9kGWoNe@dpg-d4aitdeuk2gs739g4ekg-a.oregon-postgres.render.com/testdatabase_hhx7')}

# Override for tests - use SQLite in-memory
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Denver'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'home', 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Email settings for SendGrid
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = config('SENDGRID_API_KEY')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply.harmonet@gmail.com')
SENDGRID_SANDBOX_MODE = False
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
PASSWORD_RESET_TIMEOUT = 259200

if 'test' in sys.argv:
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'



LOGIN_URL = '/login/'                  # Where to redirect if user not logged in
LOGIN_REDIRECT_URL = '/account_link/' # Where to redirect after login
LOGOUT_REDIRECT_URL = '/'              # Where to redirect after logout

OPENAI_API_KEY=config('OPENAI_API_KEY', default='')



CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
